# Site settings
title: "Aflah's Resume"
description: "Mohammad Aflah Khan's Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mohammad Aflah Khan"
resume_title:                   "Researching @ MPI-SWS, Eleuther AI & LCS2 · Incoming Analyst @ Goldman Sachs"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "aflah20082@iiitd.ac.in"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hi, I'm Aflah, a senior at IIIT-Delhi. I specialize in backend engineering, NLP, and deep learning, with a keen interest in applying NLP for social good. Currently, my research involves large language models, hate speech detection, and leveraging NLP to address various societal challenges.</p> <b>Open to researcher/research engineer roles</b>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/aflah02"
  resume_twitter_url:           "http://twitter.com/aflah02101"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mohammad-aflah-khan"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://aflah02.github.io/"
  # resume_medium_url:            "https://medium.com/@jglovier"
  resume_youtube_url:           "https://www.youtube.com/channel/UCwab-Xf38Sd7QsxVPoS0cgA"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
